src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbPlaces;

    /**
     * @ORM\ManyToMany(targetEntity=Stagiaire::class, inversedBy="sessions")
     */
    private $participer;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class, inversedBy="sessions")
     */
    private $contenir;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    public function __construct()
    {
        $this->participer = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->nom.' | '.$this->dateDebut->format('d/m/Y').' - '.$this->DateFin->format('d/m/Y');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): self
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    /**
     * @return Collection|Stagiaire[]
     */
    public function getParticiper(): Collection
    {
        return $this->participer;
    }

    public function addParticiper(Stagiaire $participer): self
    {
        if (!$this->participer->contains($participer)) {
            $this->participer[] = $participer;
        }

        return $this;
    }

    public function removeParticiper(Stagiaire $participer): self
    {
        $this->participer->removeElement($participer);

        return $this;
    }

    public function getContenir(): ?Formation
    {
        return $this->contenir;
    }

    public function setContenir(?Formation $contenir): self
    {
        $this->contenir = $contenir;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
}

src/Controller/PanelController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Module;
use App\Entity\Session;
use App\Entity\Categorie;
use App\Entity\Formation;
use App\Entity\Stagiaire;
use App\Form\AddStagiaireType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

// Normalement on écrit adminController <----


class PanelController extends AbstractController
{

   

    /**
     * @Route("/panel", name="panel_index")
     */
    public function index(): Response
    {

        $formations = $this->getDoctrine()
            ->getRepository(Formation::class)
            ->getAll();

            $modules = $this->getDoctrine()
            ->getRepository(Module::class)
            ->getAll();

            $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->getAll();

            $stagiaires = $this->getDoctrine()
            ->getRepository(Stagiaire::class)
            ->getAll();

            $categories = $this->getDoctrine()
            ->getRepository(Categorie::class)
            ->getAll();

            $sessions = $this->getDoctrine()
            ->getRepository(Session::class)
            ->getAll();

        return $this->render('panel/index.html.twig', [
            'formations' => $formations,
            'modules' => $modules,
            'users' => $users,
            'stagiaires' => $stagiaires,
            'categories' => $categories,
            'sessions' => $sessions
        ]);
    }
    
  

   

    
}

templates/panel/panel-ajouterCategorie.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Ajouter une catégorie
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# AJOUTER UNE CATEGORIE #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">

								<div class="table-responsive">
									{% set txt = (editMode) ? 'Modifier' : 'Ajouter' %}


									<h1>{{ txt }}
										une categorie
										<span>{{categorie}}</span>
									</h1>

									{{form(AddCategorieType)}}


									</div>
								</div>
							</div>
						</div>
					</div>


				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block"> © CloudLearning Panel 2020</span>
						
					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-ajouterModule.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Ajouter un module
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# TABLEAU LISTE FORMATIONS #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">

								<div class="table-responsive">
									{% set txt = (editMode) ? 'Modifier' : 'Ajouter' %}


									<h1>{{ txt }}
										un module
										<span>{{module}}</span>
									</h1>

									{{form(AddModuleType)}}


									</div>
								</div>
							</div>
						</div>
					</div>


				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block"> © CloudLearning Panel 2020</span>
						
					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-ajouterSession.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Ajouter une session
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# CARD MODIFIER SESSION #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">

								<div class="table-responsive">
									{% set txt = (editMode) ? 'Modifier' : 'Ajouter' %}


									<h1>{{ txt }}
										une session
										<span>{{session}}</span>
									</h1>

									{{form(AddSessionType)}}

									{{form(AddStagiaireType)}}


									</div>
								</div>
							</div>
						</div>
					</div>


				</div>

				
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block"> © CloudLearning Panel 2020</span>
						
					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-ajouterStagiaire.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Ajouter un(e) Stagiaire
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# TABLEAU LISTE FORMATIONS #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">

								<div class="table-responsive">
									{% set txt = (editMode) ? 'Modifier' : 'Ajouter' %}


									<h1>{{ txt }}
										un stagiaire
										<span>{{stagiaire}}</span>
									</h1>

									{{form(AddStagiaireType)}}


									</div>
								</div>
							</div>
						</div>
					</div>


				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block"> © CloudLearning Panel 2020</span>
						
					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-ajouterUser.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Ajouter un salarié
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# TABLEAU LISTE FORMATIONS #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">

								<div class="table-responsive">


									<h1>Ajouter un user
										<span>{{user}}</span>
									</h1>

									{{form(RegistrationFormType)}}


									</div>
								</div>
							</div>
						</div>
					</div>


				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
							© CloudLearning Panel 2020</span>

					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-editPassword.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Modifier mot de passe
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div class="content-wrapper">


				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">

								<div class="table-responsive">


									<h1 class="h1-pw">Modifier mon mot de passe</span>
								</h1>
								<div class="editpw-content">

									{{ form(EditPasswordType) }}
									</div>


								</div>
							</div>
						</div>
					</div>
				</div>


			</div>
			<!-- content-wrapper ends -->
			<!-- partial:partials/_footer.html -->
			<footer class="footer">
				<div class="d-sm-flex justify-content-center justify-content-sm-between">
					<span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
						© CloudLearning Panel 2020</span>

				</div>
			</footer>
			<!-- partial -->
		</div>
		<!-- main-panel ends -->
	</div>
	<!-- page-body-wrapper ends -->
</div>{% endblock %}

templates/panel/panel-editerUser.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Modifier un salarié
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# MODIFIER UN SALARIE #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">

								<div class="table-responsive">


									<h1>Modifier un salarié
										<span>{{user}}</span>
									</h1>

									{{form(EditUserType)}}


									</div>
								</div>
							</div>
						</div>
					</div>


				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
							© CloudLearning Panel 2020</span>

					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-listeCategorie.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Liste des catégories
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# TABLEAU LISTE DES CATEGORIES #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">
								<h4 class="card-title">Liste des catégories</h4>
								<div class="table-responsive">
									<table class="table">
										<thead>
											<tr>
												<th scope="col">Nom</th>
												<th scope="col">Descriptif</th>
												<th>Action</th>
											</tr>
										</thead>
										<tbody>

											{% for categorie in categories %}
												<tr>
													<td>{{categorie.nom}}</td>
													<td>{{categorie.descriptif }}</td>
													<td>
														<a href="{{ path('categorie_delete', {'id':categorie.id }) }}">
															<i class="far fa-trash-alt"></i>
														</a>
														<a href="{{ path('categorie_edit', {'id':categorie.id }) }}">
															<i class="far fa-edit"></i>
														</a>
													</td>

												{% endfor %}
											</tbody>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
							© CloudLearning Panel 2020</span>

					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-listeModule.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Liste des modules
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# TABLEAU LISTE DES MODULES #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">
								<h4 class="card-title">Liste des modules</h4>
								<div class="table-responsive">
									<table class="table">
										<thead>
											<tr>

												<th scope="col">Nom du module</th>
												<th scope="col">descriptif</th>
												<th scope="col">
													Action</th>
											</tr>
										</thead>
										<tbody>

											{% for module in modules %}

												<tr>
													<td>
														{{module.nom }}</td>
													<td>
														{{module.descriptif }}</td>
													<td>
														<a href="{{ path('module_delete', {'id':module.id }) }}">
															<i class="far fa-trash-alt"></i>
														</a>
														<a href="{{ path('module_edit', {'id':module.id }) }}">
															<i class="far fa-edit"></i>
														</a>
													</td>


												{% endfor %}
											</tbody>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
							© CloudLearning Panel 2020</span>

					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-listeSession.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Liste des sessions
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				{# TABLEAU LISTE DES SESSIONS #}
				<div class="row ">
					<div class="col-12 grid-margin">
						<div class="card">
							<div class="card-body">
								<h4 class="card-title">Liste des sessions</h4>
								<div class="table-responsive">
									<table class="table">
										<thead>
											<tr>

												<th>
													Nom de la formation
												</th>
												<th>
													Date de début
												</th>
												<th>
													Date de fin
												</th>
												<th>
													Place(s) restante
												</th>
												<th>Action</th>
											</tr>
										</thead>
										<tbody>

											{% for session in sessions %}
												<tr>
													<td>{{session.contenir.nom }}</td>
													<td>{{session.dateDebut | date("d/m/Y") }}</td>
													<td>{{session.dateFin | date("d/m/Y") }}</td>
													<td>{{session.nbPlaces }}</td>
													<td>
														<a href="{{ path('session_delete', {'id':session.id }) }}">
															<i class="far fa-trash-alt"></i>
														</a>
														<a href="{{ path('session_edit', {'id':session.id }) }}">
															<i class="far fa-edit"></i>
														</a>
													</td>

												{% endfor %}
											</tbody>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
							© CloudLearning Panel 2020</span>

					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}

templates/panel/panel-listeStagiaire.html.twig
{% extends "basePanel.html.twig" %}

{% block title %}Liste des stagiaires
{% endblock %}

{% block body %}

	<!-- partial -->

	<div
		class="container-fluid page-body-wrapper">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar p-0 fixed-top d-flex flex-row">
			<div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
				<a class="navbar-brand brand-logo-mini" href="index.html"><img src="/img/cloud_learning.png" alt="logo"/></a>
			</div>
			{# AJOUTER BOUTTON DECONNEXION ICI #}
		</nav>
		<!-- partial -->
		<div class="main-panel">
			<div
				class="content-wrapper">


				 {# TABLEAU LISTE DES STAGIAIRES #}
            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Liste des stagiaires</h4>
                    <div class="table-responsive">
                      <table class="table">
                        <thead>
                          <tr>
                          
                            <th> Nom et prénom </th>
                            <th> Email </th>
                            <th> Téléphone </th>
                            <th> Action </th>
                          </tr>
                        </thead>
                        <tbody>

                        {% for stagiaire in stagiaires %}
                           <tr>
                           
                            <td><a href="{{ path('stagiaire_show', {'id':stagiaire.id}) }}">{{ stagiaire.prenom ~' '~ stagiaire.nom }}</a></td>
                            <td> {{ stagiaire.email }} </td>
                            <td> {{ stagiaire.telephone }} </td>
                            <td><a href="{{ path('stagiaire_delete', {'id':stagiaire.id }) }}"><i class="far fa-trash-alt"></i></a> <a href="{{ path('stagiaire_edit', {'id':stagiaire.id }) }}"><i class="far fa-edit"></i></a></td>
                          </tr>
                        {% endfor %}
                         
                
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
				<!-- content-wrapper ends -->
				<!-- partial:partials/_footer.html -->
				<footer class="footer">
					<div class="d-sm-flex justify-content-center justify-content-sm-between">
						<span class="text-muted d-block text-center text-sm-left d-sm-inline-block"> © CloudLearning Panel 2020</span>
						
					</div>
				</footer>
				<!-- partial -->
			</div>
			<!-- main-panel ends -->
		</div>
		<!-- page-body-wrapper ends -->
	</div>


{% endblock %}